### ISSUE TITLE
text 출력 컨트롤러 개발

### ISSUE THREAD

**Issue by Lee-3-8** [Hokasonja/Image-to-text-converter#7]
이미지에서 텍스트로 변환된 내용을 내보내는 출력 컨트롤러를 개발한다. 

- 출력은 STRING으로 내보내짐

**Comment by 9b2n** [comment]
# 참고 자료

### 한 글자가 한 칸에 차지하는 비율
![image](https://github.com/Hokasonja/Image-to-text-converter/assets/58130501/572b6d59-c648-486e-bd4f-ee2f00faf196)
출처 : https://m.blog.naver.com/roboholic84/221256818042


### 명도에 따른 아스키 코드, 폰트별 장평 비교
![image](https://github.com/Hokasonja/Image-to-text-converter/assets/58130501/e6d6690b-1122-4fed-a7f7-eb9bcef838a9)
출처: 중앙대학교 - 프로세싱언어를 이용한 실시간 아스키 아트 작품구현 연구
